# 🏭 Concreto+ — Estudo de Caso Banco de Dados

## 1. Contexto Empresarial (Caso de Produção)

**Entidades identificadas:**
- Cliente (quem compra os lotes)
- Funcionário (quem trabalha nos lotes)
- Veículo (transporta o concreto)
- Material (cimento, areia, brita, aditivo)
- Receita (tipo de concreto e suas quantidades de material)
- Lote (produção feita em certa data)
- Remessa (entrega de um lote para um cliente)

**Relacionamentos principais:**
- Receita é formada por vários Materiais (N:N).
- Lote usa uma Receita e envolve vários Funcionários (N:N).
- Remessa leva um Lote até um Cliente usando um Veículo.

---

## 2 — Direcionamentos para o Aluno

## Etapa 1: Mapeamento Conceitual

### Entidades principais e atributos relevantes
- **Cliente** → id, nome/razão social, CNPJ, contato  
- **Funcionário** → id, nome, cargo/função  
- **Veículo** → id, placa, tipo, capacidade  
- **Material** → id, nome, unidade (kg/l)  
- **Receita** → id, nome, tipo de concreto (comum, armado etc.)  
- **Receita_Item** (tabela de ligação) → id_receita, id_material, quantidade (kg/ton)  
- **Lote** → id, data_producao, quantidade_t, status (produzido, entregue, cancelado)  
- **Lote_Funcionário** (tabela de ligação) → id_lote, id_funcionario, função no lote  
- **Remessa** → id, data_saida, quantidade, status, id_cliente, id_veiculo, id_lote  

---

### Relacionamentos identificados
- **Receita – Material (N:M)**: cada receita usa vários materiais, e cada material pode estar em várias receitas. → Resolvido pela entidade **Receita_Item**.  
- **Receita – Lote (1:N)**: um lote segue apenas uma receita, mas uma receita pode ser usada em vários lotes.  
- **Lote – Funcionário (N:M)**: vários funcionários podem trabalhar em um lote, e um funcionário pode atuar em vários lotes. → Resolvido pela entidade **Lote_Funcionário**.  
- **Lote – Remessa (1:N)**: um lote pode ser dividido em várias remessas.  
- **Remessa – Cliente (N:1)**: cada remessa é destinada a um cliente, mas um cliente pode ter várias remessas.  
- **Remessa – Veículo (N:1)**: cada remessa é transportada por um veículo, mas um veículo pode realizar várias remessas.  

---

## Etapa 2: Projeto do Diagrama Entidade-Relacionamento (DER) Conceitual

![DER Concreto+](https://private-user-images.githubusercontent.com/74316819/489341579-437260b1-1b25-438b-b81e-b155bae866c9.png?...)

## Etapa 3: Modelo Lógico (Diagrama Conceitual)

### Tabela: Cliente
- **id_cliente** (PK) → NUMBER  
- nome → VARCHAR(100) NOT NULL  
- cnpj → VARCHAR(20) UNIQUE  
- contato → VARCHAR(100)

---

### Tabela: Funcionário
- **id_funcionario** (PK) → NUMBER  
- nome → VARCHAR(100) NOT NULL  
- cargo → VARCHAR(50)

---

### Tabela: Veículo
- **id_veiculo** (PK) → NUMBER  
- placa → VARCHAR(10) NOT NULL UNIQUE  
- tipo → VARCHAR(30)  
- capacidade → NUMBER CHECK (capacidade > 0)

---

### Tabela: Material
- **id_material** (PK) → NUMBER  
- nome → VARCHAR(50) NOT NULL  
- unidade → VARCHAR(5) CHECK (unidade IN ('KG','L'))

---

### Tabela: Receita
- **id_receita** (PK) → NUMBER  
- nome → VARCHAR(50) NOT NULL UNIQUE  
- tipo → VARCHAR(30)

---

### Tabela: Receita_Item (associação N:M)
- **id_receita** (PK, FK → Receita)  
- **id_material** (PK, FK → Material)  
- quantidade → NUMBER NOT NULL CHECK (quantidade > 0)

---

### Tabela: Lote
- **id_lote** (PK) → NUMBER  
- data_producao → DATE NOT NULL  
- quantidade → NUMBER NOT NULL CHECK (quantidade > 0)  
- status → VARCHAR(20) CHECK (status IN ('PRODUZIDO','ENTREGUE','CANCELADO'))  
- id_receita (FK → Receita)

---

### Tabela: Lote_Funcionário (associação N:M)
- **id_lote** (PK, FK → Lote)  
- **id_funcionario** (PK, FK → Funcionário)  
- função → VARCHAR(50)

---

### Tabela: Remessa
- **id_remessa** (PK) → NUMBER  
- data_saida → DATE NOT NULL  
- quantidade → NUMBER NOT NULL CHECK (quantidade > 0)  
- status → VARCHAR(20) CHECK (status IN ('EM_TRANSITO','ENTREGUE','CANCELADA'))  
- id_cliente (FK → Cliente)  
- id_veiculo (FK → Veículo)  
- id_lote (FK → Lote)

---

## Normalização
- Todos os atributos não-chave dependem inteiramente da chave primária.  
- Nas tabelas de associação (**Receita_Item**, **Lote_Funcionário**), a PK é composta e os atributos (`quantidade`, `função`) dependem da chave inteira → não há dependência parcial.  
- Não há dependências transitivas.

---

## Etapa 4: Implementação Física (DDL Oracle SQL)

```sql
CREATE TABLE cliente (
  id_cliente NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome       VARCHAR2(100) NOT NULL,
  cnpj       VARCHAR2(20) UNIQUE,
  contato    VARCHAR2(100)
);

CREATE TABLE funcionario (
  id_funcionario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome           VARCHAR2(100) NOT NULL,
  cargo          VARCHAR2(50)
);

CREATE TABLE veiculo (
  id_veiculo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  placa      VARCHAR2(10) NOT NULL UNIQUE,
  tipo       VARCHAR2(30),
  capacidade NUMBER CHECK (capacidade > 0)
);

CREATE TABLE material (
  id_material NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome        VARCHAR2(50) NOT NULL,
  unidade     VARCHAR2(5) CHECK (unidade IN ('KG','L'))
);

CREATE TABLE receita (
  id_receita NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome       VARCHAR2(50) NOT NULL UNIQUE,
  tipo       VARCHAR2(30)
);

CREATE TABLE receita_item (
  id_receita  NUMBER NOT NULL,
  id_material NUMBER NOT NULL,
  quantidade  NUMBER NOT NULL CHECK (quantidade > 0),
  CONSTRAINT pk_receita_item PRIMARY KEY (id_receita, id_material),
  CONSTRAINT fk_ri_receita FOREIGN KEY (id_receita) REFERENCES receita(id_receita),
  CONSTRAINT fk_ri_material FOREIGN KEY (id_material) REFERENCES material(id_material)
);

CREATE TABLE lote (
  id_lote      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  data_producao DATE NOT NULL,
  quantidade    NUMBER NOT NULL CHECK (quantidade > 0),
  status        VARCHAR2(20) CHECK (status IN ('PRODUZIDO','ENTREGUE','CANCELADO')),
  id_receita    NUMBER NOT NULL,
  CONSTRAINT fk_lote_receita FOREIGN KEY (id_receita) REFERENCES receita(id_receita)
);

CREATE TABLE lote_funcionario (
  id_lote        NUMBER NOT NULL,
  id_funcionario NUMBER NOT NULL,
  funcao         VARCHAR2(50),
  CONSTRAINT pk_lote_funcionario PRIMARY KEY (id_lote, id_funcionario),
  CONSTRAINT fk_lf_lote FOREIGN KEY (id_lote) REFERENCES lote(id_lote),
  CONSTRAINT fk_lf_func FOREIGN KEY (id_funcionario) REFERENCES funcionario(id_funcionario)
);

CREATE TABLE remessa (
  id_remessa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  data_saida DATE NOT NULL,
  quantidade NUMBER NOT NULL CHECK (quantidade > 0),
  status     VARCHAR2(20) CHECK (status IN ('EM_TRANSITO','ENTREGUE','CANCELADA')),
  id_cliente NUMBER NOT NULL,
  id_veiculo NUMBER NOT NULL,
  id_lote    NUMBER NOT NULL,
  CONSTRAINT fk_re_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
  CONSTRAINT fk_re_veiculo FOREIGN KEY (id_veiculo) REFERENCES veiculo(id_veiculo),
  CONSTRAINT fk_re_lote FOREIGN KEY (id_lote) REFERENCES lote(id_lote)
); ```

---

## Etapa 5: Desnormalização Estratégica (Bônus Crítico)

Para facilitar relatórios de BI, podemos criar uma tabela **redundante**, que junta informações de várias tabelas em uma só.  
Essa tabela **não é usada no sistema transacional**, apenas em consultas analíticas.

### Proposta: Tabela `dm_relatorio_producao`

```sql
CREATE TABLE dm_relatorio_producao (
  id_relatorio   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  data_producao  DATE NOT NULL,
  cliente_nome   VARCHAR2(100) NOT NULL,   -- redundante
  receita_nome   VARCHAR2(50) NOT NULL,    -- redundante
  tipo_concreto  VARCHAR2(30) NOT NULL,    -- redundante
  veiculo_placa  VARCHAR2(10),             -- redundante
  quantidade     NUMBER NOT NULL,
  valor_total    NUMBER NOT NULL,
  status_entrega VARCHAR2(20)
); ```

---

## Etapa 6: Reflexão Final (Entrega Escrita)

1. **Por que a normalização foi essencial para a integridade dos dados da fábrica?**  
   A normalização elimina redundâncias (como nomes de clientes ou materiais repetidos em várias linhas) e garante consistência nas atualizações. Assim, qualquer alteração é feita em um único ponto, evitando erros e dados contraditórios. Além disso, facilita a integridade referencial, garantindo que não existam registros “soltos” sem vínculo.

2. **Em que situações a desnormalização se torna uma escolha estratégica, e não um erro?**  
   A desnormalização é estratégica quando o objetivo é melhorar o desempenho em consultas de leitura intensiva, como relatórios de BI e dashboards gerenciais. Nestes casos, sacrifica-se a integridade rígida em prol da performance, mas apenas em tabelas auxiliares de análise, nunca no sistema transacional.

3. **Quais riscos a tabela desnormalizada pode trazer? Como você mitigaria esses riscos?**  
   O principal risco é a divergência entre os dados normalizados (fonte oficial) e os dados desnormalizados (cópias redundantes). Isso pode gerar relatórios incorretos se a atualização não for bem controlada. Para mitigar, pode-se usar processos de ETL agendados, materialized views com refresh automático e rotinas de validação para garantir que os dados analíticos estejam sempre sincronizados.

4. **Qual seria o impacto de não aplicar a BCNF neste cenário?**  
   Sem a BCNF, poderiam existir determinantes que não são chaves, gerando anomalias de inserção, atualização e exclusão. Isso comprometeria a consistência da base, podendo resultar em preços incorretos, lotes duplicados ou materiais mal associados. Em um ambiente de produção e logística, esses erros teriam impacto direto na qualidade e nos custos da operação.
